### ISSUE TITLE
アイコン作成

### ISSUE THREAD

**Issue by mukko** [mukko/nodds#1]
なんか描く

**Comment by mukko** [comment]
作った

**Comment by pisgo** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
umarsa, @youyouzh, @Ralavina, @mradkov, @zalotesta, @chen2366, @jasonfengzs, @duanpeipei, @robertpaul01, @polobymulberry, @licogi, @dogexu, @nkorange, @SuperCLine, @p4vlos, @lovelacelee, @Codetector1374, @byshiny, @ShuishuaiXu, @NotGoxed, @alexismeza, @A-Ho, @herrkhalifa, @serima, @CallMeDJ, @vincentha766, @pxhszcn, @VincentGau, @zixan, @moriartyz, @yinghuochong, @robertkraig, @liveKang, @RicardAparicio, @zhangyuting, @chyonglong, @xijujie, @chenzitw, @Olliepop, @greloc, @ayush15k1994, @graham-mc, @wsc5283, @EvgeniySpinov, @SnoW-Wei, @matejd, @zarcli, @aviexk, @jysharer, @SimoneStefani

**Comment by CallMeDJ** [comment]
hello，已经收到了~
